# Generated by following instructions here
# See https://doc.qt.io/qt-5/qttestlib-tutorial1-example.html

# codebase paths
CORE = ../../maven_core
NATSORT = .
MAVEN = ../maven/

QT += testlib
TEMPLATE = app
TARGET = testqstring
INCLUDEPATH += . $$CORE/pugixml/src/ $$CORE/libmaven $$CORE/pugixml/src $$CORE/libneural $$CORE/MSToolkit/include $$CORE $$NATSORT
LIBS += -L. -L$$CORE/build/lib  -lmaven -lpugixml -lneural -lmstoolkitlite -lz

DEFINES += QT_DEPRECATED_WARNINGS

HEADERS += testsimpleparsimony.h
SOURCES += testsimpleparsimony.cpp
