# Generated by following instructions here
# See https://doc.qt.io/qt-5/qttestlib-tutorial1-example.html

# codebase paths
CORE = ../../../../maven_core
NATSORT = ../../peakdetector/
MAVEN = ../../maven

include($$CORE/libmaven.pri)

QT += core
QT += sql gui
QT -= network opengl std++14

TEMPLATE = app
TARGET = testsecprocessor

INCLUDEPATH += \
            . $$CORE/pugixml/src/ $$CORE/libmaven $$CORE/pugixml/src \
            $$CORE/libneural\
            $$CORE/MSToolkit/include\
            $$CORE \
            $$NATSORT \
            /usr/local/opt/llvm/lib/clang/13.0.1/include/

LIBS += -L. -L$$CORE/build/lib -lmaven -lpugixml -lneural -lmstoolkitlite -lz

CONFIG += sdk_no_version_check
CONFIG -= network gui opengl
CONFIG += sql qt std++14

DEFINES += QT_DEPRECATED_WARNINGS

SOURCES += testsecprocessor.cpp
