# Generated by following instructions here
# See https://doc.qt.io/qt-5/qttestlib-tutorial1-example.html
#
# Not wired into build.pro's SUBDIRS or appveyor.yml -- exercised manually
# via maven_tests.pro only.

QT += testlib sql network widgets
TEMPLATE = app
TARGET = testmzwatcher
INCLUDEPATH += . ../../mzwatcher
DEFINES += QT_DEPRECATED_WARNINGS

FORMS += ../../mzwatcher/mzWatcherGui.ui
RESOURCES += ../../mzwatcher/mzwatcher.qrc

HEADERS += ../../mzwatcher/mainWindow.h
SOURCES += testmzwatcher.cpp ../../mzwatcher/mainWindow.cpp

MOC_DIR = tmp
OBJECTS_DIR = tmp
UI_DIR = tmp
