# Generated by following instructions here
# See https://doc.qt.io/qt-5/qttestlib-tutorial1-example.html

QT += testlib
TEMPLATE = app
TARGET = testqstring
INCLUDEPATH += .
DEFINES += QT_DEPRECATED_WARNINGS

# Input
SOURCES += testqstring.cpp

